export const ContentType = "Content type"
export const ContentTypedescription = "Content type description"

export const TI = "T&I"
export const TItypeDescription = "T&I type description"

export const Locations = "Locations"
export const LocationsDescription = "Locations type description"

export const Audiences = "Audiences"
export const AudiencesDescription = "Audiences type description"

export const Needs = "Needs & subneeds"
export const NeedsDescription = "Needs type description"

export const Industries = "Industries"
export const IndustriesDescription = "Industries type description"

export const Products = "Products"
export const ProductsDescription = "Products type description"

export const Services = "Services"
export const ServicesDescription = "Services type description"

export const Topics = "Topics"
export const TopicsDescription = "Topics type description"

export const _contentType = [
    { Item: "Case studies" },
    { Item: "Client stories" },
    { Item: "Event" },
    { Item: "JLL In the news" },
    { Item: "Location" },
    { Item: "Article" },
    { Item: "Commentary" },
    { Item: "Other" },
    { Item: "People" },
    { Item: "" },
    { Item: "News release" },
    { Item: "Research" },
    { Item: "Snapshots" },
    { Item: "Views" },
    { Item: "Webinar" },
    { Item: "White paper" }
];

export const _TI = [
    { Item: "Workplace" },
    { Item: "Cities" },
    { Item: "Investor" }
];

export const _Locations = [
    { Item: "Buenos Aires", Category: "Argentina" },
    { Item: "Curitiba", Category: "Brazil" },
    { Item: "Rio de Janeiro", Category: "Brazil" },
    { Item: "Calgary", Category: "Canada" },
    { Item: "Edmonton", Category: "Canada" },
    { Item: "Vancouver", Category: "Canada" },
    { Item: "Winnipeg", Category: "Canada" },
    { Item: "Mississauga", Category: "Canada" },
    { Item: "Ottowa", Category: "Canada" },
    { Item: "Toronto", Category: "Canada" },
    { Item: "Montreal", Category: "Canada" },
    { Item: "Santiago", Category: "Chile" },
    { Item: "Bogata", Category: "Colombia" },
    { Item: "Guadalajara", Category: "Mexico" },
    { Item: "Mexico City", Category: "Mexico" },
    { Item: "Monterrey", Category: "Mexico" },
    { Item: "Tijuana", Category: "Mexico" },
    { Item: "Panama City", Category: "Panama" },
    { Item: "Lima", Category: "Peru" },
    { Item: "Puerto Rico", Category: "San Juan" },
    { Item: "Alabama", Category: "Birmingham" },
    { Item: "Alabama", Category: "Mobile" },
    { Item: "Alabama", Category: "Montgomery" },
    { Item: "Arizona", Category: "Phoenix" },
    { Item: "California", Category: "Los Angeles" },
    { Item: "California", Category: "Oakland" },
    { Item: "California", Category: "Orange County" },
    { Item: "California", Category: "Sacramento" },
    { Item: "California", Category: "San Diego" },
    { Item: "California", Category: "San Francisco" },
    { Item: "California", Category: "Silicon Valley" },
    { Item: "Colorado", Category: "Denver" },
    { Item: "Connecticut", Category: "Hartford" },
    { Item: "Connecticut", Category: "Westchester" },
];

export const _Audiences = [
    { Item: "Investors" },
    { Item: "Occupiers" },
    { Item: "Researchers" },
    { Item: "Job seekers" },
    { Item: "Shareholders" },
];

export const _Needs = [
    { Item: "Evaluate", Category: "Find and lease space" },
    { Item: "Explore", Category: "Find and lease space" },
    { Item: "Enhance", Category: "Find and lease space" },
    { Item: "Negotiate", Category: "Find and lease space" },
    { Item: "Engage", Category: "Manage property and portfolio" },
    { Item: "Enhance", Category: "Manage property and portfolio" },
    { Item: "Optimize", Category: "Manage property and portfolio" },
    { Item: "Manage or outsource", Category: "Manage property and portfolio" },
    { Item: "Consult", Category: "Deliver projects" },
    { Item: "Design", Category: "Deliver projects" },
    { Item: "Manage", Category: "Deliver projects" },
    { Item: "Build", Category: "Deliver projects" },
    { Item: "Buy", Category: "Invest in real estate" },
    { Item: "Sell", Category: "Invest in real estate" },
    { Item: "Finance", Category: "Invest in real estate" },
    { Item: "Investment banking", Category: "Invest in real estate" },
    { Item: "Lease", Category: "Invest in real estate" },
    { Item: "Value", Category: "Invest in real estate" },
    { Item: "Advise", Category: "Invest in real estate" },
    { Item: "Strategize", Category: "Transform with technology" },
    { Item: "Build", Category: "Transform with technology" },
    { Item: "Experience", Category: "Transform with technology" },
    { Item: "Invest", Category: "Transform with technology" },
    { Item: "Execute", Category: "Transform with technology" },
    { Item: "Visualize", Category: "Transform with technology" },
];

export const _Industries = [
    { Item: "Alternatives" },
    { Item: "Automotive" },
    { Item: "Banking & Finance" },
    { Item: "Contact centers" },
    { Item: "Data centers" },
    { Item: "Ecommerce" },
    { Item: "Education" },
    { Item: "Energy" },
    { Item: "Financial services" },
    { Item: "Food & Beverage" },
    { Item: "General interest" },
    { Item: "Government" },
    { Item: "Healthcare" },
    { Item: "High Street Retail" },
    { Item: "Hotels" },
    { Item: "Hotels & Hospitality" },
    { Item: "Industrial" },
    { Item: "Industrial and Logistics" },
    { Item: "Industrial & Logistics" },
    { Item: "Infrastructure" },
    { Item: "Land" },
    { Item: "Law Firms" },
    { Item: "Legal" },
    { Item: "Life Sciences" },
    { Item: "Living" },
    { Item: "Logistics" },
    { Item: "Media" },
    { Item: "Multifamily" },
    { Item: "Non-Profits" },
    { Item: "Office" },
    { Item: "Professional Services" },
    { Item: "Residential" },
    { Item: "Retail" },
    { Item: "Retail - Investment" },
    { Item: "Retirement living" },
    { Item: "Self Storage" },
    { Item: "Seniors Housing" },
    { Item: "Sports & Entertainment" },
    { Item: "Student housing" },
    { Item: "Student Housing and Higher Education" },
    { Item: "Technology" },
    { Item: "Telecommunication" },
    { Item: "Transportation" },
    { Item: "Valuation" },
];

export const _Products = [
    { Item: "3-30-300" },
    { Item: "ARCHIBUS" },
    { Item: "Asure" },
    { Item: "ATG" },
    { Item: "Blackbird" },
    { Item: "Centerstone" },
    { Item: "Command Center" },
    { Item: "Corrigo" },
    { Item: "Dronebase" },
    { Item: "ESP" },
    { Item: "FM:Systems" },
    { Item: "IBM TRIRIGA" },
    { Item: "InSite" },
    { Item: "Intellicommand" },
    { Item: "Investor App" },
    { Item: "iOffice" },
    { Item: "IWMS" },
    { Item: "JiLL" },
    { Item: "Kiosk" },
    { Item: "MapIT" },
    { Item: "Matterport" },
    { Item: "PAT" },
    { Item: "PintPoint" },
    { Item: "RED" },
    { Item: "R.E.Search" },
    { Item: "Stessa" },
    { Item: "Studio 316" },
    { Item: "Manhattan" },
    { Item: "UtilizationIQ" },
    { Item: "VR360" },
    { Item: "Wayfinding" },

];

export const _Services = [
    { Item: "1031 exchange" },
    { Item: "Accounting and finance" },
    { Item: "Appraisals" },
    { Item: "Asset management" },
    { Item: "Balance sheet reporting" },
    { Item: "Benchmarking" },
    { Item: "Brand strategy " },
    { Item: "Building consulting" },
    { Item: "Business and economic incentives " },
    { Item: "Business intelligence" },
    { Item: "Call center services" },
    { Item: "Capital markets" },
    { Item: "Capital planning" },
    { Item: "Complex litigation support" },
    { Item: "Compliance " },
    { Item: "Construction mangement" },
    { Item: "Consulting" },
    { Item: "Consumer behavior" },
    { Item: "Corporate account management" },
    { Item: "Corporate estate management" },
    { Item: "Corporate finance " },
    { Item: "Corporate solutions" },
    { Item: "Cost management" },
    { Item: "Coworking and flexible space" },
    { Item: "Create experience " },
    { Item: "Data services" },
    { Item: "Debt financing" },
    { Item: "Design and fit-out" },
    { Item: "Design management" },
    { Item: "Development management" },
    { Item: "Diagnostics and rescue" },
    { Item: "Due diligence " },
    { Item: "Energy and sustainability" },
    { Item: "Energy management" },
    { Item: "Engineering and operations" },
    { Item: "Equity financing " },
    { Item: "Feasibility and market studies" },
    { Item: "Finance" },
    { Item: "Financing counsel" },
    { Item: "Flexible facilities management" },
    { Item: "Fund advisory " },
    { Item: "Human experience " },
    { Item: "Implementation" },
    { Item: "Increase asset value" },
    { Item: "Integrated facilities management" },
    { Item: "Internet of things" },
    { Item: "Investment" },
    { Item: "Investment advice" },
    { Item: "Investment strategy " },
    { Item: "IWMS implementation" },
    { Item: "Joint ventures " },
    { Item: "Lease administration" },
    { Item: "Leasing" },
    { Item: "Lending" },
    { Item: "Loan acquisitions" },
    { Item: "Loan sales" },
    { Item: "Loan services " },
    { Item: "Location analysis " },
    { Item: "Location analysis tools " },
    { Item: "M and A strategy " },
    { Item: "Manage assets" },
    { Item: "Manage developments and projects " },
    { Item: "Manage facilities" },
    { Item: "Manage portfolio " },
    { Item: "Managed services" },
    { Item: "Mobile platforms" },
    { Item: "Monetize property" },
    { Item: "Mortgage" },
    { Item: "Net lease" },
    { Item: "Occupancy planning " },
    { Item: "Outsourcing " },
    { Item: "Plan for transitions" },
    { Item: "Planning" },
    { Item: "Portfolio analysis and BI" },
    { Item: "Portfolio diversity" },
    { Item: "Portfolio strategy " },
    { Item: "Procurement" },
    { Item: "Program management" },
    { Item: "Project leasing" },
    { Item: "Project management" },
    { Item: "Project planning" },
    { Item: "Property acquisitions" },
    { Item: "Property management" },
    { Item: "Property marketing " },
    { Item: "Property marketing tools" },
    { Item: "Property sales" },
    { Item: "Property tax consultation" },
    { Item: "Public private partnerships" },
    { Item: "Real estate asset management" },
    { Item: "Real estate sales" },
    { Item: "Redevelopment" },
    { Item: "Relocation management" },
    { Item: "Research" },
    { Item: "Reservation systems" },
    { Item: "Restructuring" },
    { Item: "Retailer strategy" },
    { Item: "Risk management" },
    { Item: "Safety" },
    { Item: "Sale and leaseback" },
    { Item: "Select operators " },
    { Item: "Site selection" },
    { Item: "Smart buildings" },
    { Item: "Software" },
    { Item: "Sourcing & supply chain management" },
    { Item: "Space planning" },
    { Item: "Strategic advisory " },
    { Item: "Structured finance" },
    { Item: "Subletting" },
    { Item: "Supply chain" },
    { Item: "Supply chain strategy " },
    { Item: "Support services" },
    { Item: "Sustainability " },
    { Item: "Technology optimization" },
    { Item: "Technology strategy" },
    { Item: "Tenant representation" },
    { Item: "Transaction management" },
    { Item: "Turnkey design and build" },
    { Item: "Valuations " },
    { Item: "Virtual test-fits and walkthroughs" },
    { Item: "Wayfinding" },
    { Item: "Workplace management" },
    { Item: "Workplace strategy" },
];

export const _Topics = [
    { Item: "3D & 4D printing" },
    { Item: "adaptive organization" },
    { Item: "advanced technologies" },
    { Item: "aging workforce" },
    { Item: "algorithmic business" },
    { Item: "Ambitions magazine" },
    { Item: "Amphitheater" },
    { Item: "Anchor store " },
    { Item: "Architecture" },
    { Item: "Artificial Intelligence" },
    { Item: "Augmented Reality" },
    { Item: "Automation" },
    { Item: "Autonomous vehicles" },
    { Item: "Baby boomers" },
    { Item: "Benchmarking" },
    { Item: "big box" },
    { Item: "Blockchain" },
    { Item: "Branding " },
    { Item: "Brexit " },
    { Item: "Brownfield" },
    { Item: "business intelligence" },
    { Item: "Business strategy" },
    { Item: "Capital flows" },
    { Item: "catering and concierge services" },
    { Item: "Change management" },
    { Item: "Changing workforce" },
    { Item: "Climate change" },
    { Item: "Cloud technology" },
    { Item: "Cold storage" },
    { Item: "College campus" },
    { Item: "community" },
    { Item: "Compliance " },
    { Item: "construction " },
    { Item: "consumer expectations" },
    { Item: "Continuous innovation" },
    { Item: "Convention centers" },
    { Item: "corporate social responsibility" },
    { Item: "Cost Management" },
    { Item: "Cost of living " },
    { Item: "CRE tech " },
    { Item: "cross collaborations" },
    { Item: "Currency" },
    { Item: "Cybersecurity" },
    { Item: "Data & analytics " },
    { Item: "Davos" },
    { Item: "demand planning" },
    { Item: "Demographics " },
    { Item: "Design " },
    { Item: "Digital" },
    { Item: "Digital drive " },
    { Item: "Digitization" },
    { Item: "Diversity " },
    { Item: "Downstream" },
    { Item: "Drones" },
    { Item: "Ecommerce" },
    { Item: "Economic insights" },
    { Item: "Economics" },
    { Item: "Economy " },
    { Item: "efficiency" },
    { Item: "Elections" },
    { Item: "Employee engagement " },
    { Item: "Employee happiness" },
    { Item: "Employee wellness" },
    { Item: "employment" },
    { Item: "energy and sustainability" },
    { Item: "Environment" },
    { Item: "Ethics" },
    { Item: "experience" },
    { Item: "experience applications" },
    { Item: "Expert opinion" },
    { Item: "EXPO" },
    { Item: "Featured" },
    { Item: "Financial performance" },
    { Item: "fractured reporting" },
    { Item: "frictionless workplace" },
    { Item: "Future of work" },
    { Item: "future skilling" },
    { Item: "Generation X" },
    { Item: "Generation Z" },
    { Item: "Gig economy" },
    { Item: "Global capital" },
    { Item: "Globalization" },
    { Item: "Government subsidies" },
    { Item: "Green + productive " },
    { Item: "Greenfield" },
    { Item: "GSA" },
    { Item: "hot markets " },
    { Item: "HSSE (Health, Safety, Security & Environment) " },
    { Item: "Human experience " },
    { Item: "humanization" },
    { Item: "hybrid environments" },
    { Item: "image and brand" },
    { Item: "Incubators" },
    { Item: "Industrial outlook" },
    { Item: "Innovation " },
    { Item: "innovation culture" },
    { Item: "integrated business services" },
    { Item: "Internet of things" },
    { Item: "Investment outlook" },
    { Item: "Investment strategy " },
    { Item: "IWMS" },
    { Item: "JLL Spark " },
    { Item: "labor" },
    { Item: "Last mile " },
    { Item: "lease accounting changes" },
    { Item: "Lease negotiation" },
    { Item: "liquid workforce" },
    { Item: "Local" },
    { Item: "Location strategy " },
    { Item: "London office markets" },
    { Item: "M&A strategy " },
    { Item: "Machine learning " },
    { Item: "maintenance" },
    { Item: "Mall" },
    { Item: "MAPIC" },
    { Item: "Market statistics " },
    { Item: "Market trends" },
    { Item: "metrics that matter" },
    { Item: "Midstream" },
    { Item: "Millennials" },
    { Item: "MIPIM" },
    { Item: "MIT" },
    { Item: "Mobility " },
    { Item: "Moving" },
    { Item: "Museum" },
    { Item: "NASA" },
    { Item: "networked solutions and open innovation" },
    { Item: "new leadership models emerging" },
    { Item: "Not featured" },
    { Item: "Occupancy planning" },
    { Item: "Office outlook" },
    { Item: "Offshoring" },
    { Item: "oil and gas" },
    { Item: "Omnishoring" },
    { Item: "On prem" },
    { Item: "Open office " },
    { Item: "Operational excellence " },
    { Item: "outsourcing" },
    { Item: "Politics " },
    { Item: "Portfolio flexibility" },
    { Item: "Power center " },
    { Item: "predictive analytics" },
    { Item: "predictive maintenance " },
];