export const ContentType = "Content type"
export const ContentTypedescription = "Content type description"

export const TI = "T&I"
export const TItypeDescription = "T&I type description"

export const Locations = "Locations"
export const LocationsDescription = "Locations type description"

export const Audiences = "Audiences"
export const AudiencesDescription = "Audiences type description"

export const Needs = "Needs & subneeds"
export const NeedsDescription = "Needs type description"

export const Industries = "Industries"
export const IndustriesDescription = "Industries type description"

export const Products = "Products"
export const ProductsDescription = "Products type description"

export const Services = "Services"
export const ServicesDescription = "Services type description"

export const Topics = "Topics"
export const TopicsDescription = "Topics type description"

export const _contentType = [
    { Item: "Case studies" },
    { Item: "Client stories" },
    { Item: "Event" },
    { Item: "JLL In the news" },
    { Item: "Location" },
    { Item: "Article" },
    { Item: "Commentary" },
    { Item: "People" }
    { Item: "News release" },
    { Item: "Research" },
    { Item: "Snapshots" },
    { Item: "Views" },
    { Item: "Webinar" },
    { Item: "White paper" },    
    { Item: "Other" }
];

export const _TI = [
    { Item: "Workplace" },
    { Item: "Cities" },
    { Item: "Investor" }
];

export const _Locations = [
    { Item: "Buenos Aires", Category: "Argentina" },
    { Item: "Curitiba", Category: "Brazil" },
    { Item: "Rio de Janeiro", Category: "Brazil" },
    { Item: "Calgary", Category: "Canada" },
    { Item: "Edmonton", Category: "Canada" },
    { Item: "Vancouver", Category: "Canada" },
    { Item: "Winnipeg", Category: "Canada" },
    { Item: "Mississauga", Category: "Canada" },
    { Item: "Ottowa", Category: "Canada" },
    { Item: "Toronto", Category: "Canada" },
    { Item: "Montreal", Category: "Canada" },
    { Item: "Santiago", Category: "Chile" },
    { Item: "Bogata", Category: "Colombia" },
    { Item: "Guadalajara", Category: "Mexico" },
    { Item: "Mexico City", Category: "Mexico" },
    { Item: "Monterrey", Category: "Mexico" },
    { Item: "Tijuana", Category: "Mexico" },
    { Item: "Panama City", Category: "Panama" },
    { Item: "Lima", Category: "Peru" },
    { Item: "Puerto Rico", Category: "San Juan" },
    { Item: "Alabama", Category: "Birmingham" },
    { Item: "Alabama", Category: "Mobile" },
    { Item: "Alabama", Category: "Montgomery" },
    { Item: "Arizona", Category: "Phoenix" },
    { Item: "California", Category: "Los Angeles" },
    { Item: "California", Category: "Oakland" },
    { Item: "California", Category: "Orange County" },
    { Item: "California", Category: "Sacramento" },
    { Item: "California", Category: "San Diego" },
    { Item: "California", Category: "San Francisco" },
    { Item: "California", Category: "Silicon Valley" },
    { Item: "Colorado", Category: "Denver" },
    { Item: "Connecticut", Category: "Hartford" },
    { Item: "Connecticut", Category: "Westchester" },
];

export const _Audiences = [
    { Item: "Investors" },
    { Item: "Occupiers" },
    { Item: "Researchers" },
    { Item: "Job seekers" },
    { Item: "Shareholders" },
];

export const _Needs = [
    { Item: "Evaluate", Category: "Find and lease space" },
    { Item: "Explore", Category: "Find and lease space" },
    { Item: "Enhance", Category: "Find and lease space" },
    { Item: "Negotiate", Category: "Find and lease space" },
    { Item: "Engage", Category: "Manage property and portfolio" },
    { Item: "Enhance", Category: "Manage property and portfolio" },
    { Item: "Optimize", Category: "Manage property and portfolio" },
    { Item: "Manage or outsource", Category: "Manage property and portfolio" },
    { Item: "Consult", Category: "Deliver projects" },
    { Item: "Design", Category: "Deliver projects" },
    { Item: "Manage", Category: "Deliver projects" },
    { Item: "Build", Category: "Deliver projects" },
    { Item: "Buy", Category: "Invest in real estate" },
    { Item: "Sell", Category: "Invest in real estate" },
    { Item: "Finance", Category: "Invest in real estate" },
    { Item: "Investment banking", Category: "Invest in real estate" },
    { Item: "Lease", Category: "Invest in real estate" },
    { Item: "Value", Category: "Invest in real estate" },
    { Item: "Advise", Category: "Invest in real estate" },
    { Item: "Strategize", Category: "Transform with technology" },
    { Item: "Build", Category: "Transform with technology" },
    { Item: "Experience", Category: "Transform with technology" },
    { Item: "Invest", Category: "Transform with technology" },
    { Item: "Execute", Category: "Transform with technology" },
    { Item: "Visualize", Category: "Transform with technology" },
];

export const _Industries = [
    { Item: "Alternatives" },
    { Item: "Automotive" },
    { Item: "Banking & Finance" },
    { Item: "Contact centers" },
    { Item: "Data centers" },
    { Item: "Ecommerce" },
    { Item: "Education" },
    { Item: "Energy" },
    { Item: "Financial services" },
    { Item: "Food & Beverage" },
    { Item: "General interest" },
    { Item: "Government" },
    { Item: "Healthcare" },
    { Item: "High Street Retail" },
    { Item: "Hotels" },
    { Item: "Hotels & Hospitality" },
    { Item: "Industrial" },
    { Item: "Industrial and Logistics" },
    { Item: "Industrial & Logistics" },
    { Item: "Infrastructure" },
    { Item: "Land" },
    { Item: "Law Firms" },
    { Item: "Legal" },
    { Item: "Life Sciences" },
    { Item: "Living" },
    { Item: "Logistics" },
    { Item: "Media" },
    { Item: "Multifamily" },
    { Item: "Non-Profits" },
    { Item: "Office" },
    { Item: "Professional Services" },
    { Item: "Residential" },
    { Item: "Retail" },
    { Item: "Retail - Investment" },
    { Item: "Retirement living" },
    { Item: "Self Storage" },
    { Item: "Seniors Housing" },
    { Item: "Sports & Entertainment" },
    { Item: "Student housing" },
    { Item: "Student Housing and Higher Education" },
    { Item: "Technology" },
    { Item: "Telecommunication" },
    { Item: "Transportation" },
    { Item: "Valuation" },
];

export const _Products = [
    { Item: "3-30-300" },
    { Item: "ARCHIBUS" },
    { Item: "Asure" },
    { Item: "ATG" },
    { Item: "Blackbird" },
    { Item: "Centerstone" },
    { Item: "Command Center" },
    { Item: "Corrigo" },
    { Item: "Dronebase" },
    { Item: "ESP" },
    { Item: "FM:Systems" },
    { Item: "IBM TRIRIGA" },
    { Item: "InSite" },
    { Item: "Intellicommand" },
    { Item: "Investor App" },
    { Item: "iOffice" },
    { Item: "IWMS" },
    { Item: "JiLL" },
    { Item: "Kiosk" },
    { Item: "MapIT" },
    { Item: "Matterport" },
    { Item: "PAT" },
    { Item: "PintPoint" },
    { Item: "RED" },
    { Item: "R.E.Search" },
    { Item: "Stessa" },
    { Item: "Studio 316" },
    { Item: "Manhattan" },
    { Item: "UtilizationIQ" },
    { Item: "VR360" },
    { Item: "Wayfinding" },

];

export const _Services = [
    { Item: "Agency Leasing" },
    { Item: "Agency Lending" },
    { Item: "Asset management " },
    { Item: "Benchmarking" },
    { Item: "Building consulting" },
    { Item: "Business intelligence " },
    { Item: "Business and economic incentives" },
    { Item: "Capital markets" },
    { Item: "Capital planning" },
    { Item: "Commissioning & Building Analytics" },
    { Item: "Compliance" },
    { Item: "Construction management " },
    { Item: "Consulting" },
    { Item: "Corporate finance" },
    { Item: "Corporate Finance & Net Lease" },
    { Item: "Corporate solutions" },
    { Item: "Cost management" },
    { Item: "Coworking and flexible space" },
    { Item: "Create experience" },
    { Item: "Debt Advisory" },
    { Item: "Debt financing" },
    { Item: "Debt Placement" },
    { Item: "Design and fit-out" },
    { Item: "Development management" },
    { Item: "Due diligence " },
    { Item: "Energy and sustainability" },
    { Item: "Energy & Sustainability Services" },
    { Item: "Engineering and operations" },
    { Item: "Equity & Advisory" },
    { Item: "Facilities Management" },
    { Item: "Feasibility and market studies" },
    { Item: "Finance" },
    { Item: "Fund advisory" },
    { Item: "Human experience" },
    { Item: "Investment strategy" },
    { Item: "Investment Advisory" },
    { Item: "Investment Sales and Acquisitions" },
    { Item: "Investment" },
    { Item: "Lease Administration" },
    { Item: "Leasing" },
    { Item: "Loan acquisitions" },
    { Item: "Loan Sales" },
    { Item: "Loan Servicing" },
    { Item: "Location analysis" },
    { Item: "Logistics & Supply Chain Management" },
    { Item: "Merger & Acquisition Advice" },
    { Item: "Net lease" },
    { Item: "Occupancy planning" },
    { Item: "Office Agency" },
    { Item: "Outsourcing" },
    { Item: "Planning" },
    { Item: "Portfolio strategy" },
    { Item: "Procurement" },
    { Item: "Program Management" },
    { Item: "Project & Development Services" },
    { Item: "Project management" },
    { Item: "Property and Asset Management" },
    { Item: "Property management" },
    { Item: "Property marketing" },
    { Item: "Public private partnerships " },
    { Item: "Real estate sales " },
    { Item: "Redevelopment" },
    { Item: "Relocation management" },
    { Item: "Research" },
    { Item: "Restructuring " },
    { Item: "Retail Sales and Leasing" },
    { Item: "Risk management" },
    { Item: "Sale and leaseback" },
    { Item: "Site selection" },
    { Item: "Space Planning" },
    { Item: "Strategic advisory" },
    { Item: "Strategic Consulting" },
    { Item: "Supply chain strategy" },
    { Item: "Technology optimization" },
    { Item: "Tenant representation" },
    { Item: "Tetris" },
    { Item: "Transaction management" },
    { Item: "Valuation Advisory" },
    { Item: "Valuation and Advisory" },
    { Item: "Valuations" },
    { Item: "Workplace management" },
    { Item: "Workplace strategy" },

];

export const _Topics = [
    { Item: "Architecture" },
    { Item: "Automation" },
    { Item: "big box" },
    { Item: "Brexit " },
    { Item: "Building Places" },
    { Item: "Business strategy" },
    { Item: "Capital flows" },
    { Item: "Climate change" },
    { Item: "Cold storage" },
    { Item: "community" },
    { Item: "consumer expectations" },
    { Item: "corporate social responsibility" },
    { Item: "COVID-19" },
    { Item: "COVID-19 community stories" },
    { Item: "Cybersecurity" },
    { Item: "Davos" },
    { Item: "demand planning" },
    { Item: "Demographics" },
    { Item: "Design" },
    { Item: "Diversity" },
    { Item: "Ecommerce" },
    { Item: "Economic insights" },
    { Item: "Economy" },
    { Item: "Employee engagement" },
    { Item: "employment" },
    { Item: "Ethics" },
    { Item: "experience" },
    { Item: "EXPO" },
    { Item: "Featured" },
    { Item: "Financial Performance" },
    { Item: "Flexible space" },
    { Item: "Future of work" },
    { Item: "Gig economy" },
    { Item: "Globalization" },
    { Item: "GMP" },
    { Item: "GRETI" },
    { Item: "GSA" },
    { Item: "Guy Grainger" },
    { Item: "(HSSE) Health, Safety, Security & Environment" },
    { Item: "Human experience" },
    { Item: "hybrid environments" },
    { Item: "Industrial outlook" },
    { Item: "Innovation" },
    { Item: "Investment outlook" },
    { Item: "Investor perspectives" },
    { Item: "JLL Spark" },
    { Item: "Last mile" },
    { Item: "lease accounting changes" },
    { Item: "Local" },
    { Item: "Location strategy" },
    { Item: "Market trends" },
    { Item: "MIPIM" },
    { Item: "MIT" },
    { Item: "Mobility" },
    { Item: "Office outlook" },
    { Item: "Offshoring" },
    { Item: "Operational excellence" },
    { Item: "Podcast" },
    { Item: "Politics" },
    { Item: "private public partnerships" },
    { Item: "Productivity" },
    { Item: "Property predictions" },
    { Item: "Prop Tech" },
    { Item: "Real estate strategy" },
    { Item: "Regulation" },
    { Item: "reimagine" },
    { Item: "REIT" },
    { Item: "Remote work" },
    { Item: "Renewable Energy" },
    { Item: "Reposition" },
    { Item: "Repurpose real estate" },
    { Item: "Smart cities" },
    { Item: "Startup" },
    { Item: "Stories of ambition" },
    { Item: "Sustainability" },
    { Item: "Talent" },
    { Item: "Taxes & tariffs" },
    { Item: "Tourism" },
    { Item: "Upstream" },
    { Item: "Urban infill" },
    { Item: "Urbanization" },
    { Item: "Utilization" },
    { Item: "Wellness" },
    { Item: "Women Inspire" },
    { Item: "Workplace strategy" },
    { Item: "World Economic Forum" },
];